### ISSUE TITLE
Replicate OPT-125M BabyLM benchmark

### ISSUE THREAD

**Issue by venkatasg** [venkatasg/Lil-Bevo#1]
BabyLM provides ['naive' benchmarks](https://github.com/babylm/evaluation-pipeline#baselines) &mdash; OPT-125M is the closest model to the template that I have setup, which is based on [nanoGPT][https://github.com/karpathy/nanoGPT/tree/master] by Andrej Karpathy. A good first step is to see if we can replicate the OPT-125M benchmark with the template and workflow we have. The nanoGPT template should enable us to go as low level as we need to.

## Sub-tasks:

- [x] Tokenization should be implemented in pipeline. Perhaps tokenize data and save?
- [x] Set up logging with `wandb` to track everything while training.
- [x] Reproduce GPT2 (124M) architecture and optimize for training resources that we do have.
- [x] Benchmark on Strict-small
- [x] Benchmark on Strict

**Comment by venkatasg** [comment]
Kind of replicated - keep pretraining to exactly replicate the benchmarks.

**Comment by venkatasg** [comment]
Kind of replicated - keep pretraining to exactly replicate the benchmarks.
