### ISSUE TITLE
Stuff we want to try for loose track

### ISSUE THREAD

**Issue by venkatasg** [venkatasg/Lil-Bevo#4]
Stuff we want to try for loose track.

## Sub-tasks:

- [ ] Can we use models trained on a larger amount of data to identify training dataset?
- [ ] RLHF w/ GPT4 output
- [ ] Generate texts from GPT4 based on the current model’s predictions.
- [ ] Symbolic distillation 
- [ ] cheat and put BLIMP / SuperGLUE stuff there

**Comment by venkatasg** [comment]
Didn't try.
